model_set:
  # 模型名称
  MODEL_NAME: "qwen2.5:7b"
  # 模型模式 local 本地 ; cloud 云端
  PATTERN: "local"
  # 启用轮询机制 True False
  POLLING: "True"
  # 最大轮询次数
  MAX_RETRIES: 3

server_set:
  # auto 自动配置（Automatic configuration） ; 或者强制指定（Fixed ip address）
  host_ip: "auto"
  # 端口
  post: 8000
  # 公开服务 false true
  public: "false"
  # Development、dp、Dp 开发模式； Test、test 测试模式
  mode: "Development"

deepseek:
  API_KEY: ""
  BASE_URL: "https://api.deepseek.com"
  MAX_TOKEN: 50000
  MODEL: "deepseek-reasoner"

siliconflow:
  MODEL: "Qwen/QwQ-32B"
  MAX_TOKEN: 32768
  API_KEY: ""
  BASE_URL: "https://api.siliconflow.cn/v1/"


github_set:
  # github token
  token: ""


logging:
  level: "INFO"
  file: "./logs/app.log"
